# 指定 Go 镜像
FROM golang:1.17-alpine

WORKDIR /goweb

# 设置环境变量
ENV BUILD_ENV local
ENV TZ=Asia/Shanghai

# 暴露端口
EXPOSE 8080


ADD . ./
ENV GO111MODULE=on
ENV GOPROXY https://goproxy.cn

RUN go build -o demo main.go

EXPOSE 8080
CMD ["/goweb/demo"]
